routes/web.php
<?php

Auth::routes();
Route::view('/', 'homepage');
Route::get('home', 'HomeController@index')->name('home');

Route::middleware(['auth', 'MuridRole'])->group(function(){
	Route::prefix('murid')->group(function() {
		Route::name('murid.')->group(function(){
			Route::get('room', 'VideoRoomController@indexMurid')->name('room.index');
			Route::post('room/join', 'VideoRoomController@joinRoomMurid')->name('room.join');
			Route::get('dashboard','ProfileController@indexMurid')->name('index');
			Route::get('detail/{id}','OrderController@detailOrderMurid')->name('detail');
			Route::get('detail/delete/{id}', 'OrderController@hapusOrderan')->name('hapusOrderan');
			Route::get('les/offline/order','OrderController@createOffline')->name('createOffline');
			Route::post('les/offline/order','OrderController@createOfflinePost')->name('createOfflinePost');
			Route::put('les/offline/accept/{id}', 'OrderController@createOfflineAccepted')->name('createOfflineAccepted');
			Route::post('les/offline/finish','OrderController@createOfflineFinished')->name('createOfflineFinished');
			Route::get('les/online/order','OrderController@createOnline')->name('createOnline');
			Route::post('les/online/order','OrderController@createOnlinePost')->name('createOnlinePost');
			Route::get('les/materi/search','MateriController@searchMateri')->name('searchMateri');
			Route::post('les/materi/search','MateriController@searchMateriPost')->name('searchMateriPost');
			Route::get('materi/{id}','MateriController@materi')->name('materi');
			Route::get('materi/{id}/sertifikat','MateriController@printSertifikat')->name('printSertifikat');
			Route::get('task','OrderController@taskMurid')->name('taskMurid');
			Route::get('settings','HomeController@settingsMurid')->name('settingsMurid');
			Route::post('deposit','ProfileController@depositMuridAction')->name('depositMuridAction');
			Route::get('profile','ProfileController@profileMurid')->name('profileMurid');
			Route::get('isiprofile','ProfileController@isiProfileMurid')->name('isiProfileMurid');
			Route::post('isiprofile','ProfileController@isiProfileMuridAction')->name('isiProfileMuridAction');
			Route::get('updateprofile/{id}','ProfileController@updateProfileMurid')->name('updateProfileMurid');
			Route::post('updateprofile','ProfileController@updateProfileMuridAction')->name('updateProfileMuridAction');
			Route::post('buyvideo','MyVideosController@buyVideo')->name('buyVideo');
			Route::get('watch/{title}', 'MateriController@watchmateri')->name('watch');
		});
	});
});
Route::middleware(['auth', 'GuruRole'])->group(function(){
	Route::prefix('guru')->group(function(){
		Route::name('guru.')->group(function(){
			Route::get('room', 'VideoRoomController@indexGuru')->name('room.index');
			Route::get('room/join/{roomName}', 'VideoRoomController@joinRoom')->name('group.room.join');
			Route::post('room/create', 'VideoRoomController@createRoom')->name('room.create');
			Route::get('dashboard','ProfileController@indexGuru')->name('index');
			Route::get('les/offline/order','MateriController@searchOffline')->name('searchOffline');
			Route::get('les/offline/order/{id}','MateriController@searchOfflineDetail')->name('searchOfflineDetail');
			Route::post('les/offline/order','MateriController@searchOfflineAction')->name('searchOfflineTake');
			Route::get('les/offline/filter','MateriController@searchOfflineFilter')->name('searchOfflineFilter');
			Route::post('les/offline/proses','MateriController@searchOfflineProcess')->name('searchOfflineProses');
			Route::post('les/offline/finish','MateriController@searchOfflineFinished')->name('searchOfflineFinished');
			Route::get('les/online/order','MateriController@searchOnline')->name('searchOnline');
			Route::get('les/online/order/{id}','MateriController@searchOnlineDetail')->name('searchOnlineDetail');
			Route::get('les/materi/create','MateriController@createMateri')->name('createMateri');
			Route::post('les/materi/create','MateriController@createMateriPost')->name('createMateriPost');
			Route::get('task','OrderController@taskGuru')->name('taskGuru');
			Route::get('settings','HomeController@settingsGuru')->name('settingsGuru');
			Route::get('withdraw','ProfileController@withdrawGuru')->name('withdrawGuru');
			Route::post('withdraw','ProfileController@withdrawGuruAction')->name('withdrawGuruAction');
			Route::get('profile','ProfileController@profileGuru')->name('profileGuru');
			Route::get('isiprofile','ProfileController@isiProfileGuru')->name('isiProfileGuru');
			Route::post('isiprofile','ProfileController@isiProfileGuruAction')->name('isiProfileGuruAction');
			Route::get('updateprofile/{id}','ProfileController@updateProfileGuru')->name('updateProfileGuru');
			Route::post('updateprofile','ProfileController@updateProfileGuruAction')->name('updateProfileGuruAction');
		});
	});
});

resources/views/guru/createMateri.blade.php
@extends('layouts.master_guru')
@section('title', 'Buat Materi')
@section('content')
<div class="container py-4" id="form_buat_materi">
  <form method="POST" action="{{ route('guru.createMateriPost') }}" class="card shadow bg-white p-4" enctype="multipart/form-data">
    <h1 class="h3 mb-4 font-weight-bold text-dark">Buat Materi Untuk Dapat Dijelajahi Murid</h1>
    @csrf
    <div class="form-row">
      <div class="form-group col-12 col-md-6">
        <label for="judul" class="text-dark">Judul Materi</label>
        <input id="judul" type="text" class="form-control" name="judul" placeholder="Berikan Judul Materimu Agar Mudah Dicari" required>
      </div>
      <div class="form-group col-12 col-md-6">
        <label for="lesco" class="text-dark">Tarif Lesco</label>
        <input id="lesco" type="number" class="form-control" placeholder="Berapa Harga Materimu" name="lesco" required>
      </div>
      <div class="form-group col-12 col-md-6">
        <label for="" class="d-block">Upload Video</label>
        <input type="file" name="videos" required>
      </div>
      <div class="form-group col-12 col-md-6">
        <label for="picturePost">Thumbnail :</label>
        <div class="custom-file">
          <input type="file" class="custom-file-input" name="sampul" id="customFile">
          <label class="custom-file-label" for="customFile">Choose file</label>
        </div>
      </div>
    </div>
    <div class="form-group">
      <label for="jenjang">Untuk Jenjang</label>
      <select class="custom-select" name="jenjang" id="jenjang">
        <option value="TK">TK</option>
        <option value="SD">SD / Sederajat</option>
        <option value="SMP">SMP / Sederajat</option>
        <option value="SMA">SMA / Sederajat</option>
      </select>
    </div>
    <div class="form-group">
      <label for="deskripsi" class="text-dark">Deskripsi Materi</label>
      <textarea class="form-control" id="deskripsi" name="deskripsi" placeholder="Detail Materimu Apa Sih" rows="7" required></textarea>
    </div>
    <div class="d-flex justify-content-between">
      <a href="{{ url()->previous() }}" class="no-underline text-danger"><i class='bx bx-arrow-back pr-3'></i>Back To Previous Page</a>
      <button type="submit" class="btn btn-success py-2">Buat Materi</button>
    </div>
    </form>
  </div>
  @endsection
  @section('footer_all')
    @include('partials.footer')
  @endsection

resources/views/guru/hasil_filter.blade.php
@extends('layouts.master_guru')
@section('title', 'Hasil Pencarian')
@section('content')
<div class="container py-5" id="hasil_cari">
  <div class="row position-relative justify-content-between align-items-start m-0 height-full">
    <!-- filter guru ditampilan tablet dan desktop -->
    <aside class="col-12 col-md-3 card shadow-sm px-1 py-3">
      <form action="{{ route('guru.searchOfflineFilter') }}" method="get" class="p-3">
        <div class="mb-4">
          <label for="jenjang">Jenjang Sekolah</label>
          <select name="jenjang" id="jenjang" class="custom-select">
            <option value="" selected>Semua Jenjang</option>
            @foreach ($orders as $filters)
              @if ($filters->jenjang === 'SD')
              <option value="SD" selected>SD</option>
              <option value="SMP">SMP</option>
              <option value="SMA">SMA</option>
              <option value="SMK">SMK</option>
              @else
              <option value="SMP" selected>SMP</option>
              <option value="SMK">SMK</option>
              <option value="SD">SD</option>
              <option value="SMA">SMA</option>
              @endif
            @endforeach
          </select>
        </div>
        <div class="mb-4">
          <label for="matpel">Mata Pelajaran</label>
          <select name="pelajaran" id="matpel" class="custom-select">
            <option value="" selected>Semua Pelajaran</option>
            <option value="Bahasa Indonesia">Bahasa Indonesia</option>
            <option value="Matematika">Matematika</option>
            <option value="Bahasa Inggris">Bahasa Inggris</option>
            <option value="IPA">IPA</option>
            <option value="IPS">IPS</option>
            <option value="Others">Others</option>
          </select>
        </div>
        <div class="mb-4">
          <label for="kategori_pelajaran">Materi Pelajaran</label>
          <input type="search" name="materi" class="form-control" placeholder="Cari Materi Pelajaran" id="kategori_pelajaran">
        </div>
        <button type="submit" name="button" class="btn btn-success w-100">Cari Murid</button>
      </form>
    </aside>
    <!-- end of filter guru ditampilan tablet dan desktop-->
    <section class="col-12 col-md-8 float-right">
      <div class="row flex-column">
        @foreach($filter as $hasil)
          <article class="col-12 mb-3 card shadow-sm p-0">
            <figure class="m-0 p-3 height-full">
              <img src="{{ asset('photoguru/' . $hasil->orderOwner->profileMurid->photo) }}" height="50" class="float-left mr-3">
              <figcaption class="position-relative">
                <strong class="d-block">{{ $hasil->orderOwner->name }}</strong>
                <em class="d-block text-secondary my-1">Nama Pelajaran <strong>{{ $hasil->pelajaran }}</strong></em>
                <em class="d-block text-secondary my-1 materi_pelajaran">Materi Pelajaran <strong>{{ $hasil->kategori_pelajaran }}</strong></em>
                <span class="text-info text-capitalize">
                  harga : <var class="font-weight-bold" style="color: #DE891A;">{{ $hasil->lesco }} Lesco</var>
                </span>
              </figcaption>
            </figure>
            <div class="py-2 text-center border-top" style="background-color: #D0D0D0;">
              <a href="{{ route('guru.searchOfflineDetail', $hasil->id) }}">Lihat Lebih Lanjut</a>
            </div>
          </article>
        @endforeach
      </div>
    </section>
  </div>
</div>
@endsection
@section('footer_all')
  @include('partials.footer')
@endsection
@section('script')
  <script>
  $(document).ready(function(){
    //form search
    var productSource = [
      @foreach ($orders as $order)
         "{{ $order->kategori_pelajaran }}",
      @endforeach
    ];
    $("input[name='kategori_pelajaran']").autocomplete({
      source: productSource
    });
  });
  </script>
@endsection

resources/views/guru/index.blade.php
@extends('layouts.master_guru')
@section('title', 'Cari Guru Sesuai Keinginanmu')
@section('header')
  @if (count($profil) == 0)
    <div class="alert alert-danger text-center" role="alert">
    Kamu tidak bisa memulai mengajar dan melakukan withdraw <b>Coin Lesco</b> sebelum melengkapi profil. <a href="{{ route('guru.profileGuru') }}">Lengkapi sekarang</a>
  </div>
  @endif
  <header>
    <div class="container">
      <h1 id="header_slogan">Selamat Datang, <strong>{{ Auth::user()->name }}</strong></h1>
      <div class="row mb-5">
        @if (count($profil) == 0)
        <div class="col-2">
          <a href="{{ route('guru.searchOffline') }}" class="btn disabled" aria-disabled="true">
            <i class='h1 mb-1 bx bx-search-alt'></i>
            Temukan Murid
          </a>
        </div>
        <div class="col-2">
          <a href="{{ route('guru.createMateri') }}" class="btn disabled" aria-disabled="true">
            <i class='h1 mb-1 bx bx-plus'></i>
            Buat Materi
          </a>
        </div>
        <div class="col-2">
          <a href="{{ route('guru.profileGuru') }}" class="btn disabled" aria-disabled="true">
            <i class='h1 mb-1 bx bx-user'></i>
            Profile
          </a>
        </div>
        @else
          <div class="col-2">
            <a href="{{ route('guru.searchOffline') }}" class="btn">
                <i class='h1 mb-1 bx bx-search-alt'></i>
                Temukan Murid
            </a>
          </div>
          <div class="col-2">
            <a href="{{ route('guru.createMateri') }}" class="btn">
              <i class='h1 mb-1 bx bx-plus'></i>
              Buat Materi
            </a>
          </div>
          <div class="col-2">
            <a href="{{ route('guru.profileGuru') }}" class="btn">
              <i class='h1 mb-1 bx bx-user'></i>
              Profile
            </a>
          </div>
        @endif
      </div>
      <div class="row">
      @if(count($profil) > 0)
      @foreach($profil as $profile)
        <div class="col-6">
          @if (empty($profile->lesco))
          <div class="d-flex py-3 px-4 justify-content-between align-items-center">
            <span class="h5 mb-0">Lesco Cash<var class="d-block text-left"><sup>Lc</sup>0</var></span>
            <a href="javascript:void(0);" class="btn btn-dark shadow-sm show-modal disabled" aria-disabled="true">Withdraw Lesco</a>
            <div class="modal-custom-overlay">
              <div class="modal-custom">
                <div class="modal-custom-header">
                  <h1 class="h2">Withdraw Lescomu</h1>
                </div>
                <div class="modal-custom-body">
                  @include('guru.withdraw')
                </div>
              </div>
            </div>
          </div>
          @else
          <div class="d-flex py-3 px-4 justify-content-between align-items-center">
            <span class="h5 mb-0">Lesco Cash<var class="d-block text-left"><sup>Lc</sup>{{ $profile->lesco }}</var></span>
            <a href="javascript:void(0);" class="btn btn-dark shadow-sm show-modal">Withdraw Lesco</a>
            <div class="modal-custom-overlay">
              <div class="modal-custom">
                <div class="modal-custom-header">
                  <h1 class="h2">Withdraw Lescomu</h1>
                </div>
                <div class="modal-custom-body">
                  @include('guru.withdraw')
                </div>
              </div>
            </div>
          </div>
          @endif
        </div>
        @endforeach
        @else
          <div class="col-6">
            <div class="d-flex py-3 px-4 justify-content-between align-items-center">
              <span class="h5 mb-0">Lesco Cash<var class="d-block text-left"><sup>Lc</sup>0</var></span>
              <a href="javascript:void(0);" class="btn btn-dark shadow-sm show-modal disabled" aria-disabled="true">Withdraw Lesco</a>
              <div class="modal-custom-overlay">
                <div class="modal-custom">
                  <div class="modal-custom-header">
                    <h1 class="h2">Withdraw Lescomu</h1>
                  </div>
                  <div class="modal-custom-body">
                    @include('guru.withdraw')
                  </div>
                </div>
              </div>
            </div>
          </div>
        @endif
      </div>
    </div>
  </header>
@endsection
@section('footer_all')
  @include('partials.footer')
@endsection

resources/views/guru/profile.blade.php
@extends('layouts.master_guru')
@section('title', 'Profile Kamu')
@section('content')

<div class="container py-5" id="profile_page">
    <div class="row m-0 align-items-start">
      <aside class="col-4 bg-white rounded border">
          <figure class="text-center my-3">
            @isset($profil)
            <a class="btn d-block mb-4 shadow-sm" href="{{ route('guru.updateProfileGuru', $profil->id) }}">Perbarui Profilmu</a>
            @endisset
            @empty($profil)
              <a href="{{ route('guru.isiProfileGuru') }}" class="btn d-block mb-4 shadow-sm">Lengkapi Profilmu</a>
            @endempty
            @isset($profil)
            <img src="{{ asset('photoguru/'.$profil->photo) }}" height="90" class="d-block mt- mx-auto">
            <figcaption class="font-weight-bold py-2">
              <span class="d-block">{{ Auth::user()->name }}</span>
              <small class="text-secondary">Jumlah Lesco: {{ $profil->lesco }}</small>
            </figcaption>
            @endisset
            @empty($profil)
            <img src="{{ asset('photoguru/people.png') }}" height="90" class="d-block mt- mx-auto">
            <figcaption class="font-weight-bold py-2">
              <span class="d-block">{{ Auth::user()->name }}</span>
              <small class="text-secondary">Jumlah Lesco: 0</small>
            </figcaption>
            @endempty
          </figure>
        <div id="people_details" class="border-top">
          <h1 class="h5 my-3 text-dark">Informasi Pribadimu</h1>
          <ul class="m-0">
            <li class="py-2">
              <label class="d-block text-secondary">Email Kamu</label>
              <small class="font-weight-bold">{{ Auth::user()->email }}</small>
            </li>
            <li class="py-2">
              <label class="d-block text-secondary">Nomor Telepon</label>
              @isset($profil)
              <small class="font-weight-bold">{{ $profil->phone }}</small>
              @endisset
            </li>
            <li class="py-2">
              <label class="d-block text-secondary">Alamat</label>
              @isset($profil)
              <address class="font-weight-bold m-0">{{ $profil->alamat }}</address>
              @endisset
            </li>
              <li class="py-2">
                <label for="" class="d-block text-secondary">KTP</label>
                @isset($profil)
                  <var class="font-weight-bold">{{ $profil->ktp }}</var>
                @endisset
                @empty($profil)
                  <span class="font-weight-bold">. . . .</span>
                @endempty
              </li>
            <li class="py-2">
              <label class="d-block text-secondary">Nomor Rekening</label>
              @isset($profil)
              <var class="font-weight-bold text-normal" style="font-style: normal;">{{ $profil->norek }}</var>
              @endisset
            </li>
            <li class="py-2">
              <label class="d-block text-secondary">Tentang Kamu</label>
              @isset($profil)
              <p class="font-weight-bold">{{ $profil->tentang }}</p>
              @endisset
              @empty($profil)
              <span class="font-weight-bold">. . . . </span>
              @endempty
            </li>
          </ul>
        </div>
      </aside>
      <section class="col ml-5 bg-white px-0 border">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" id="orderan-tab" data-toggle="tab" href="#orderan" role="tab" aria-controls="orderan" aria-selected="true">Riwayat</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="video-tab" data-toggle="tab" href="#video" role="tab" aria-controls="video" aria-selected="false">Materi</a>
          </li>
        </ul>
        <div class="tab-content" id="myTabContent">
          <div class="tab-pane p-4 fade show active" id="orderan" role="tabpanel" aria-labelledby="orderan-tab">
            @if (count($history) > 0)
              @foreach ($history as $pelajaran)
                <article class="card shadow-sm col px-0 mb-3">
                  <div class="d-flex justify-content-between px-3 pt-3 pb-1">
                    <p class="font-weight-bold">{{ $pelajaran->pelajaran }}</p>
                    <time class="font-italic">{{ $pelajaran->created_at->format('d F Y') }}</time>
                  </div>
                  <div class="d-flex justify-content-between px-3 pt-1 pb-3">
                    <p class="m-0">{{ $pelajaran->studentname }}</p>
                    <span>Tarif Lesco: <var>{{ $pelajaran->lesco }}</var></span>
                  </div>
                </article>
              @endforeach
            @else
              <div class="alert alert-warning text-capitalize col" role="alert">
                Kamu belum memiliki orderan apapun
              </div>
            @endif
          </div>
          <div class="tab-pane p-4 fade" id="video" role="tabpanel" aria-labelledby="video-tab">
            @if (count($videos) > 0)
              @foreach ($videos as $video)
                <article class="card shadow-sm col px-0">
                  <div class="d-flex justify-content-between px-3 pt-3 pb-1">
                    <p class="font-weight-bold">{{{ $video->judul }}}</p>
                  </div>
                  <div class="d-flex justify-content-between px-3 pt-1 pb-3">
                    <span>Tarif Lesco: <var>{{ $video->lesco }} Lesco</var></span>
                  </div>
                  <div class="action bg-light text-center p-2">
                    <a href="{{ asset('uploaded_video/'.$video->video) }}" target="_blank">Lihat Detail</a>
                  </div>
                </article>
              @endforeach
              {{ $videos->links('vendor.pagination.bootstrap-4') }}
            @else
              <div class="alert alert-warning text-capitalize col" role="alert">
                Kamu belum pernah membagikan video
              </div>
            @endif
          </div>
        </div>
      </section>
    </div>
  </div>

@endsection

@section('footer_all')
  @include('partials.footer')
@endsection

resources/views/guru/searchOffline.blade.php
@extends('layouts.master_guru')
@section('title', 'Hasil Pencarian')
@section('content')
<div class="container py-5" id="hasil_cari">
  <div class="row position-relative justify-content-between align-items-start m-0 height-full">
    <!-- filter guru ditampilan tablet dan desktop -->
    <aside class="col-12 col-md-3 card shadow-sm px-1 py-3">
      <form action="{{ route('guru.searchOfflineFilter') }}" method="get" class="p-3">
        <div class="mb-4">
          <label for="jenjang">Jenjang Sekolah</label>
          <select name="jenjang" id="jenjang" class="custom-select">
            <option value="" disabled selected>Semua Jenjang</option>
            <option value="SD">SD</option>
            <option value="SMP">SMP</option>
            <option value="SMA">SMA</option>
            <option value="SMK">SMK</option>
          </select>
        </div>
        <div class="mb-4">
          <label for="matpel">Mata Pelajaran</label>
          <select name="pelajaran" id="matpel" class="custom-select">
            <option value="" selected>Semua Pelajaran</option>
            <option value="Bahasa Indonesia">Bahasa Indonesia</option>
            <option value="Matematika">Matematika</option>
            <option value="Bahasa Inggris">Bahasa Inggris</option>
            <option value="IPA">IPA</option>
            <option value="IPS">IPS</option>
            <option value="Others">Others</option>
          </select>
        </div>
        <div class="mb-4">
          <label for="kategori_pelajaran">Materi Pelajaran</label>
          <input type="search" name="materi" class="form-control" placeholder="Cari Materi Pelajaran" id="kategori_pelajaran">
        </div>
        <button type="submit" name="button" class="btn btn-success w-100">Cari Murid</button>
      </form>
    </aside>
    <!-- end of filter guru ditampilan tablet dan desktop-->
    <section class="col-12 col-md-8 float-right">
      <div class="row flex-column">
        @foreach($orders as $order)
          <article class="col-12 mb-3 card shadow-sm p-0">
            <figure class="m-0 p-3 height-full">
              <img src="{{ asset('photoguru/' . $order->orderOwner->profileMurid->photo) }}" height="50" class="float-left mr-3">
              <figcaption class="position-relative">
                <strong class="d-block">{{ $order->orderOwner->name }}</strong>
                <em class="d-block text-secondary my-1">Nama Pelajaran <strong>{{ $order->pelajaran }}</strong></em>
                <em class="d-block text-secondary my-1 materi_pelajaran">
                  Materi Pelajaran <strong>{{ $order->kategori_pelajaran }}</strong>
                </em>
                <span class="text-info text-capitalize">
                  harga : <var class="font-weight-bold" style="color: #DE891A;">{{ $order->lesco }} Lesco</var>
                </span>
              </figcaption>
            </figure>
            <div class="py-2 text-center border-top" style="background-color: #D0D0D0;">
              <a href="{{ route('guru.searchOfflineDetail', $order->id) }}">Lihat Lebih Lanjut</a>
            </div>
          </article>
        @endforeach
      </div>
    </section>
  </div>
</div>
@endsection
@section('footer_all')
  @include('partials.footer')
@endsection
@section('script')
  <script>
  $(document).ready(function(){
    //form search
    var productSource = [
      @foreach ($orders as $order)
         "{{ $order->kategori_pelajaran }}",
      @endforeach
    ];
    $("input[name='kategori_pelajaran']").autocomplete({
      source: productSource
    });
  });
  </script>
@endsection

resources/views/guru/searchOfflineDetail.blade.php
@extends('layouts.master_guru')
@section('title', 'Detail Order')
@section('content')
  <div class="container py-0" id="order_page">
    <div class="row">
      <div class="col-12 col-md-4 order-md-2 py-md-5">
        <figure class="p-3 p-md-0 m-0 text-center position-relative" style="top: 10%;transform: translateY(-50%)">
          <img src="{{ asset('photoguru/' . $orderan->orderOwner->profileMurid->photo) }}" height="90">
          <figcaption class="pt-2 text-center mt-0">
            <h2 class="m-0">{{ $orderan->teachername }}</h2>
            <p class="text-success font-weight-bold m-0">Status : {{ $orderan->status }}</p>
            <p class="text-info m-0 font-weight-bold">
              Nomor Murid :
              <a  class="text-info" href="tel:{{ $orderan->orderOwner->profileMurid->phone }}">
                {{ $orderan->orderOwner->profileMurid->phone }}
              </a>
            </p>
          </figcaption>
        </figure>
      </div>
      <div class="col-12 col-md-8 py-5 order-md-1">
        <h1 class="col-12 px-0 pb-md-4 h3 text-dark font-weight-bold">Detail Pemesanan {{ $orderan->created_at->format('d F Y') }}</h1>
        <div class="row">
          <div class="col">
            <p class="text-secondary">
              Mata Pelajaran <br>
              <span class="text-success font-weight-bold text-capitalize">{{ $orderan->pelajaran }}</span>
            </p>
          </div>
          <div class="col">
            <p class="text-secondary">
              Materi Pelajaran <br>
              <span class="text-success font-weight-bold text-capitalize">{{ $orderan->kategori_pelajaran }}</span>
            </p>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <p class="text-secondary">
              Jenjang Pendidikan <br>
              <span class="text-success font-weight-bold text-uppercase">{{ $orderan->orderOwner->profileMurid->jenjang }}</span>
            </p>
          </div>
          <div class="col">
            <p class="text-secondary">
              Tipe Pesanan Guru <br>
              <span class="text-success font-weight-bold text-capitalize">Les {{ $orderan->type }}</span>
            </p>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <p class="text-secondary">Durasi<br><span class="text-success font-weight-bold">{{ $orderan->durasi }} Jam</span></p>
          </div>
          <div class="col">
            <p class="text-secondary">Tarif Lesco<br><span class="text-success font-weight-bold">{{ $orderan->lesco }} Coin</span></p>
          </div>
        </div>
        @if ($orderan->type == 'Offline')
        <div class="row">
          <div class="col">
            <label class="text-secondary mb-1">Alamat Ketemuan</label>
            <address class="font-weight-bold text-success">{{ $orderan->alamat_ketemu }}</address>
          </div>
        </div>
        @endif
        <div class="row mb-3" id="deskripsi_pesanan">
          <div class="col">
            <label for="deskripsi" class="text-secondary">Deskripsi Pesanan</label>
            <p class="text-success font-weight-bold text-capitalize">{{ $orderan->deskripsi }}</p>
          </div>
        </div>
        @if ($orderan->status == "Waiting")
        <div class="row mx-0">
          <form action="{{ route('murid.createOfflineAccepted', $orderan->id) }}" method="post">
            @csrf @method('PUT')
            <input type="hidden" name="idOrder" value="{{ $orderan->id }}">
            <button type="submit" class="btn btn-success">Terima Tawaran</button>
          </form>
        </div>
        @elseif($orderan->status === "Process")
        <form action="{{ route('murid.createOfflineFinished') }}" method="post">
          @csrf
          <input type="hidden" class="form-control" value="{{ $orderan->id }}" name="idOrder">
          <button type="submit" class="btn btn-danger">Sudahi Belajar</button>
        </form>
        @endif
      </div>
    </div>
  @endsection
  @section('footer_all')
    @include('partials.footer')
  @endsection