routes/web.php
<?php

Auth::routes();
Route::view('/', 'homepage');
Route::get('home', 'HomeController@index')->name('home');

Route::middleware(['auth', 'MuridRole'])->group(function(){
	Route::prefix('murid')->group(function() {
		Route::name('murid.')->group(function(){
			Route::get('room', 'VideoRoomController@indexMurid')->name('room.index');
			Route::post('room/join', 'VideoRoomController@joinRoomMurid')->name('room.join');
			Route::get('dashboard','ProfileController@indexMurid')->name('index');
			Route::get('detail/{id}','OrderController@detailOrderMurid')->name('detail');
			Route::get('detail/delete/{id}', 'OrderController@hapusOrderan')->name('hapusOrderan');
			Route::get('les/offline/order','OrderController@createOffline')->name('createOffline');
			Route::post('les/offline/order','OrderController@createOfflinePost')->name('createOfflinePost');
			Route::put('les/offline/accept/{id}', 'OrderController@createOfflineAccepted')->name('createOfflineAccepted');
			Route::post('les/offline/finish','OrderController@createOfflineFinished')->name('createOfflineFinished');
			Route::get('les/online/order','OrderController@createOnline')->name('createOnline');
			Route::post('les/online/order','OrderController@createOnlinePost')->name('createOnlinePost');
			Route::get('les/materi/search','MateriController@searchMateri')->name('searchMateri');
			Route::post('les/materi/search','MateriController@searchMateriPost')->name('searchMateriPost');
			Route::get('materi/{id}','MateriController@materi')->name('materi');
			Route::get('materi/{id}/sertifikat','MateriController@printSertifikat')->name('printSertifikat');
			Route::get('task','OrderController@taskMurid')->name('taskMurid');
			Route::get('settings','HomeController@settingsMurid')->name('settingsMurid');
			Route::post('deposit','ProfileController@depositMuridAction')->name('depositMuridAction');
			Route::get('profile','ProfileController@profileMurid')->name('profileMurid');
			Route::get('isiprofile','ProfileController@isiProfileMurid')->name('isiProfileMurid');
			Route::post('isiprofile','ProfileController@isiProfileMuridAction')->name('isiProfileMuridAction');
			Route::get('updateprofile/{id}','ProfileController@updateProfileMurid')->name('updateProfileMurid');
			Route::post('updateprofile','ProfileController@updateProfileMuridAction')->name('updateProfileMuridAction');
			Route::post('buyvideo','MyVideosController@buyVideo')->name('buyVideo');
			Route::get('watch/{title}', 'MateriController@watchmateri')->name('watch');
		});
	});
});
Route::middleware(['auth', 'GuruRole'])->group(function(){
	Route::prefix('guru')->group(function(){
		Route::name('guru.')->group(function(){
			Route::get('room', 'VideoRoomController@indexGuru')->name('room.index');
			Route::get('room/join/{roomName}', 'VideoRoomController@joinRoom')->name('group.room.join');
			Route::post('room/create', 'VideoRoomController@createRoom')->name('room.create');
			Route::get('dashboard','ProfileController@indexGuru')->name('index');
			Route::get('les/offline/order','MateriController@searchOffline')->name('searchOffline');
			Route::get('les/offline/order/{id}','MateriController@searchOfflineDetail')->name('searchOfflineDetail');
			Route::post('les/offline/order','MateriController@searchOfflineAction')->name('searchOfflineTake');
			Route::get('les/offline/filter','MateriController@searchOfflineFilter')->name('searchOfflineFilter');
			Route::post('les/offline/proses','MateriController@searchOfflineProcess')->name('searchOfflineProses');
			Route::post('les/offline/finish','MateriController@searchOfflineFinished')->name('searchOfflineFinished');
			Route::get('les/online/order','MateriController@searchOnline')->name('searchOnline');
			Route::get('les/online/order/{id}','MateriController@searchOnlineDetail')->name('searchOnlineDetail');
			Route::get('les/materi/create','MateriController@createMateri')->name('createMateri');
			Route::post('les/materi/create','MateriController@createMateriPost')->name('createMateriPost');
			Route::get('task','OrderController@taskGuru')->name('taskGuru');
			Route::get('settings','HomeController@settingsGuru')->name('settingsGuru');
			Route::get('withdraw','ProfileController@withdrawGuru')->name('withdrawGuru');
			Route::post('withdraw','ProfileController@withdrawGuruAction')->name('withdrawGuruAction');
			Route::get('profile','ProfileController@profileGuru')->name('profileGuru');
			Route::get('isiprofile','ProfileController@isiProfileGuru')->name('isiProfileGuru');
			Route::post('isiprofile','ProfileController@isiProfileGuruAction')->name('isiProfileGuruAction');
			Route::get('updateprofile/{id}','ProfileController@updateProfileGuru')->name('updateProfileGuru');
			Route::post('updateprofile','ProfileController@updateProfileGuruAction')->name('updateProfileGuruAction');
		});
	});
});

resources/views/murid/cariMateri.blade.php
@extends('layouts.master_siswa')
@section('title', 'Hasil Pencarian')
@section('content')
<div class="container py-4" id="search_materi">
  <form method="POST" action="{{ route('murid.searchMateriPost') }}" class="my-3 mb-5">
    @csrf
    <div class="form-group col-12 position-relative px-0">
      <input id="materi" type="text" class="form-control" name="materi" placeholder="Apa yang ingin kamu pelajari" required>
      <button type="submit" class="btn shadow-none" name="button"><i class='bx bx-search-alt'></i></button>
    </div>
  </form>
  <hr>
  <h1 class="h3 my-4">Materi Yang Disarankan Untukmu</h1>
  @foreach ($videonya as $video)
    <form action="{{ route('murid.buyVideo') }}" method="POST">
      @csrf
      <input type="hidden" value="{{ $video->id }}" class="form-control" name="idvideo" id="idvideo">
      <input type="hidden" value="{{ $video->guru }}" class="form-control" name="guru" id="guru">
      <input type="hidden" value="{{ $video->judul }}" class="form-control" name="judul" id="judul">
      <input type="hidden" value="{{ $video->deskripsi }}" class="form-control" name="deskripsi" id="deskripsi">
      <input type="hidden" value="{{ $video->video }}" class="form-control" name="video" id="video">
      <input type="hidden" value="{{ $video->sampul }}" class="form-control" name="sampul" id="sampul">
      <input type="hidden" value="{{ $video->lesco }}" class="form-control" name="lesco" id="lesco">
      <div class="card p-0 col-12 shadow-sm mb-3">
        <div class="card-body p-0">
          <figure class="d-flex m-0">
            <img class="col-md-4 px-0 border-right" height="150" src="{{ asset('sampul/'.$video->sampul)}}" style="object-fit: cover;">
            <figcaption class="position-relative col py-3">
              <h5 class="card-title">{{ $video->judul }}</h5>
              <p class="card-text">{{ $video->deskripsi }}</p>
              <var>Harga {{ $video->lesco }} Lesco</var>
              <button type="submit" name="button" class="btn btn-success">Beli Video</button>
            </figcaption>
          </figure>
        </div>
      </div>
    </form>
  @endforeach
</div>
@endsection
@section('footer_all')
@include('partials.footer')
@endsection

resources/views/murid/createOffline.blade.php
@extends('layouts.master_siswa')
@section('title', 'Order Guru')
@section('content')
<div class="container py-4" id="cari_guru">
    <form action="{{ route('murid.createOfflinePost') }}" class="card shadow bg-white p-4" method="POST">
      <h1 class="h3 font-weight-bold mb-4">Panggil Guru Sesuai Keinginanmu</h1>
      @csrf
      <input type="hidden" name="nmr_murid" value="{{ $profil->phone }}">
      <input type="hidden" name="photo_murid" value="{{ $profil->photo }}">
      <div class="form-row">
        <div class="form-group col-12 col-md-6">
          <select name="pelajaran" id="matpel" class="custom-select" autofocus required>
            <option value="" selected disabled>Mata Pelajaran</option>
            <option value="Bahasa Indonesia">Bahasa Indonesia</option>
            <option value="Matematika">Matematika</option>
            <option value="Bahasa Inggris">Bahasa Inggris</option>
            <option value="IPA">IPA</option>
            <option value="IPS">IPS</option>
            <option value="Others">Others</option>
          </select>
        </div>
        <div class="form-group col-12 col-md-6">
          <select class="custom-select" name="durasi" required>
            <option value="" selected disabled>Durasi</option>
            <option value="1">1 Jam</option>
            <option value="2">2 Jam</option>
            <option value="3">3 Jam</option>
            <option value="4">4 Jam</option>
            <option value="5">5 Jam</option>
          </select>
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-12 col-md-6">
          <input type="number" min="1" max="{{ $profil->lesco }}" class="form-control" id="lesco" name="lesco" placeholder="Tarif Lesco" required>
        </div>
        <div class="form-group col-12 col-md-6">
          <select name="jenjang" id="jenjang" class="custom-select" required>
            <option value="" selected disabled>Jenjang</option>
            <option value="SD">SD</option>
            <option value="SMP">SMP</option>
            <option value="SMK">SMK</option>
          </select>
        </div>
      </div>
      <div class="form-group col-12 px-0">
        <input type="text" name="kategori_pelajaran" class="form-control text-capitalize" placeholder="Materi Apa Yang Kamu Inginkan (contoh: Aljabar)" required>
      </div>
      <div class="form-group col-12 px-0">
        <textarea name="deskripsi" rows="6" class="form-control" placeholder="Deskripsi" required></textarea>
      </div>
      <div class="form-group col-12 px-0">
        <textarea name="alamat" rows="6" minlength="5" class="form-control" placeholder="Alamat Ketemuan" required></textarea>
        <div class="custom-control custom-checkbox mt-3">
          <input type="checkbox" name="alamat_rumah" class="custom-control-input" id="alamat_rumah">
          <label class="custom-control-label" for="alamat_rumah">Pergunakan alamat rumah saya</label>
        </div>
      </div>
      <div class="form-row justify-content-between">
        <button type="reset" name="button" class="btn btn-warning text-white shadow-sm">Hapus Semua</button>
        <button type="submit" name="button" class="btn btn-success">Buat Order</button>
      </div>
    </form>
  </div>
</div>
@endsection
@section('footer_all')
  @include('partials.footer')
@endsection
@section('script')
  <script>
    $("input[name='alamat_rumah']").change(function() {
      if ($(this).is(":checked")) {
        $(this).parent().prev().val("{{ $profil->alamat }}").prop("readonly", true);
      }
      else {
        $(this).parent().prev().val("").prop("readonly", false);
      }
    });
  </script>
@endsection

resources/views/murid/dashboard.blade.php
@extends('layouts.master_siswa')
@section('title', 'Cari Guru Sesuai Keinginanmu')
@section('header')
  @empty($profil)
    <div class="alert alert-danger text-center" role="alert">
    Kamu tidak bisa melakukan pemesanan guru dan topup <b>Coin Lesco</b> Sebelum melengkapi profil. <a href="{{ route('murid.profileMurid') }}">Lengkapi sekarang</a>
  </div>
  @endempty
<header>
  <div class="container">
    <h1 id="header_slogan">Selamat Datang, <strong>{{ Auth::user()->name }}</strong></h1>
    <div class="row mb-5">
      @isset($profil)
        @empty($profil)
          <div class="col-2">
            <a href="{{ route('murid.createOffline') }}" class="btn disabled" aria-disabled="true">
              <i class='h1 mb-1 bx bx-search-alt'></i>
              Pesan Guru
            </a>
          </div>
          <div class="col-2">
            <a href="{{ route('murid.searchMateri') }}" class="btn disabled" aria-disabled="true">
              <i class='h1 mb-1 bx bxl-youtube'></i>
              Jelajah Materi
            </a>
          </div>
          <div class="col-2">
            <a href="{{ route('murid.profileMurid') }}" class="btn">
              <i class='h1 mb-1 bx bx-user'></i>
              Profile
            </a>
          </div>
        @endempty
        @isset($profil)
            @if ($profil->lesco > 1)
              <div class="col-2">
                  <a href="{{ route('murid.createOffline') }}" class="btn">
                    <i class='h1 mb-1 bx bx-search-alt'></i>
                    Pesan Guru
                  </a>
              </div>
              <div class="col-2">
                <a href="{{ route('murid.searchMateri') }}" class="btn">
                  <i class='h1 mb-1 bx bxl-youtube'></i>
                  Jelajah Materi
                </a>
              </div>
              <div class="col-2">
                <a href="{{ route('murid.profileMurid') }}" class="btn">
                  <i class='h1 mb-1 bx bx-user'></i>
                  Profile
                </a>
              </div>
            @else
              <div class="col-2">
                  <a href="{{ route('murid.createOffline') }}" class="btn disabled" aria-disabled="true">
                    <i class='h1 mb-1 bx bx-search-alt'></i>
                    Pesan Guru
                  </a>
              </div>
              <div class="col-2">
                <a href="{{ route('murid.searchMateri') }}" class="btn disabled" aria-disabled="true">
                  <i class='h1 mb-1 bx bxl-youtube'></i>
                  Jelajah Materi
                </a>
              </div>
              <div class="col-2">
                <a href="{{ route('murid.profileMurid') }}" class="btn">
                  <i class='h1 mb-1 bx bx-user'></i>
                  Profile
                </a>
              </div>
            @endif
        @endif
      @endisset
      @empty($profil)
        <div class="col-2">
          <a href="{{ route('murid.createOffline') }}" class="btn disabled" aria-disabled="true">
            <i class='h1 mb-1 bx bx-search-alt'></i>
            Pesan Guru
          </a>
        </div>
        <div class="col-2">
          <a href="{{ route('murid.searchMateri') }}" class="btn disabled" aria-disabled="true">
            <i class='h1 mb-1 bx bxl-youtube'></i>
            Jelajah Materi
          </a>
        </div>
        <div class="col-2">
          <a href="{{ route('murid.profileMurid') }}" class="btn">
            <i class='h1 mb-1 bx bx-user'></i>
            Profile
          </a>
        </div>
      @endempty
    </div>
    <div class="row">
      <div class="col-6">
        <div class="d-flex py-3 px-4 justify-content-between align-items-center">
          <span class="h5 mb-0 text-white">Lesco Cash
            <var class="d-block text-left">
              <sup>Lc</sup> @if ($profil->lesco == 0) 0 @else {{ $profil->lesco }} @endif
            </var>
          </span>
          <a href="javascript:void(0)" class="btn btn-dark shadow-sm show-modal">Top Up Lesco</a>
          <div class="modal-custom-overlay">
            <div class="modal-custom">
              <div class="modal-custom-header">
                <h1 class="h2">Topup Lescomu</h1>
              </div>
              <div class="modal-custom-body">
                @include('murid.topup')
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
@endsection
@section('footer_top')
  @include('partials.footer_top')
@endsection

resources/views/murid/detailOrder.blade.php
@extends('layouts.master_siswa')
@section('title', 'Detail Order')
@section('content')
<div class="container py-0" id="order_page">
  <div class="row">
    <div class="col-12 col-md-4 order-md-2 py-md-5">
      <figure class="p-3 p-md-0 m-0 text-center position-relative" style="top: 10%;transform: translateY(-50%)">
        <img src="{{ asset('photoguru/'.$orders->photo_murid) }}" height="90" alt="" class="">
        <figcaption class="pt-2 text-center mt-0">
          <h2 class="m-0">{{ $orders->teachername }}</h2>
          <span class="text-success font-weight-bold">Status : {{ $orders->status }}</span>
          @if ($orders->type == 'Offline')
          <address class="font-weight-bold m-0 text-primary">
            Alamat Ketemuan : {{ $orders->alamat }}
          </address>
          @endif
        </figcaption>
      </figure>
    </div>
    <div class="col-12 col-md-8 py-5 order-md-1">
      <h1 class="col-12 px-0 pb-md-4 h3 text-dark font-weight-bold">Detail Pemesanan {{ $orders->created_at->format('d F Y') }}</h1>
        <div class="row">
          <div class="col">
            <p class="text-secondary">Mata Pelajaran<br><span class="text-success font-weight-bold text-capitalize">{{ $orders->pelajaran }}</span></p>
          </div>
          <div class="col">
            <p class="text-secondary">Materi Pelajaran<br><span class="text-success font-weight-bold text-capitalize">{{ $orders->kategori_pelajaran }}</span></p>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <p class="text-secondary">Jenjang Pendidikan<br><span class="text-success font-weight-bold text-uppercase">{{ $orders->jenjang }}</span></p>
          </div>
          <div class="col">
            <p class="text-secondary">Tipe Pesanan Guru<br><span class="text-success font-weight-bold text-capitalize">Les {{ $orders->type }}</span></p>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <p class="text-secondary">Durasi<br><span class="text-success font-weight-bold">{{ $orders->durasi }} Jam</span></p>
          </div>
          <div class="col">
            <p class="text-secondary">Tarif Lesco<br><span class="text-success font-weight-bold">{{ $orders->lesco }} Coin</span></p>
          </div>
        </div>
        @if ($orders->type == 'Offline')
        <div class="row">
          <div class="col">
            <label class="text-secondary mb-1">Alamat Ketemuan</label>
            <address class="font-weight-bold text-success">{{ $orders->alamat }}</address>
          </div>
        </div>
        @endif
        <div class="row mb-3" id="deskripsi_pesanan">
          <div class="col">
            <label for="deskripsi" class="text-secondary">Deskripsi Pesanan</label>
            <p class="text-success font-weight-bold text-capitalize">{{ $orders->deskripsi }}</p>
          </div>
        </div>
        @if ($orders->status === "Waiting")
        <div class="row mx-0">
          <a href="{{ route('murid.hapusOrderan', $orders->id) }}" class="btn btn-danger">Hapus Orderan Ini</a>
        </div>
        @elseif($orders->status === "Process")
        <form action="{{ route('murid.createOfflineFinished') }}" method="post">
          @csrf
          <input type="hidden" class="form-control" value="{{ $orders->id }}" name="idOrder">
          <button type="submit" name="button" class="btn btn-danger">Sudahi Belajar</button>
        </form>
        @endif
    </div>
  </div>
  @endsection
  @section('footer_all')
    @include('partials.footer')
  @endsection

resources/views/murid/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in as a student!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/murid/profile.blade.php
@extends('layouts.master_siswa')
@section('title', 'Profile Kamu')
@section('content')

<div class="container py-5" id="profile_page">
  <div class="row m-0 align-items-start">
    <aside class="col-4 bg-white rounded border">
      <figure class="text-center my-3">
        @isset($profil)
          <a class="btn d-block mb-4 shadow-sm" href="{{ route('murid.updateProfileMurid', $profil->id) }}">Perbarui Profilmu</a>
        @endisset
        @empty($profil)
          <a href="{{ route('murid.isiProfileMurid') }}" class="btn d-block mb-4 shadow-sm">Lengkapi Profilmu</a>
        @endempty
        @isset($profil)
          <img src="{{ asset('photoguru/'.$profil->photo) }}" height="90" class="d-block mt- mx-auto">
          <figcaption class="font-weight-bold py-2">
            <span class="d-block">{{ Auth::user()->name }}</span>
            <small class="text-secondary">Jumlah Lesco: {{ $profil->lesco }}</small>
          </figcaption>
        @endisset
        @empty($profil)
          <img src="{{ asset('photoguru/people.png') }}" height="90" class="d-block mt- mx-auto">
          <figcaption class="font-weight-bold py-2">
            <span class="d-block">{{ Auth::user()->name }}</span>
            <small class="text-secondary">Jumlah Lesco: 0</small>
          </figcaption>
        @endempty
      </figure>
      <div id="people_details" class="border-top">
        <h1 class="h5 my-3 text-dark">Informasi Pribadimu</h1>
        <ul class="m-0">
          <li class="py-2">
            <label class="d-block text-secondary">Email Kamu</label>
            <small class="font-weight-bold">{{ Auth::user()->email }}</small>
          </li>
          <li class="py-2">
            <label class="d-block text-secondary">Nomor Telepon</label>
            @isset($profil)
              <small class="font-weight-bold">{{ $profil->phone }}</small>
            @endisset
            @empty($profil)
              <span class="font-weight-bold">. . . .</span>
            @endempty
          </li>
          <li class="py-2">
            <label class="d-block text-secondary">Alamat</label>
            @isset($profil)
              <address class="font-weight-bold m-0">{{ $profil->alamat }}</address>
            @endisset
            @empty($profil)
              <span class="font-weight-bold">. . . .</span>
            @endempty
          </li>
          <li class="py-2">
            <label for="" class="d-block text-secondary">NISN</label>
            @isset($profil)
              <var class="font-weight-bold">{{ $profil->nisn }}</var>
            @endisset
            @empty($profil)
              <span class="font-weight-bold">. . . .</span>
            @endempty
          </li>
          <li class="py-2">
            <label class="d-block text-secondary">Nomor Rekening</label>
            @isset($profil)
              <var class="font-weight-bold text-normal" style="font-style: normal;">{{ $profil->norek }}</var>
            @endisset
            @empty($profil)
              <span class="font-weight-bold">. . . .</span>
            @endempty
          </li>
          <li class="py-2">
            <label class="d-block text-secondary">Tentang Kamu</label>
            @isset($profil)
              <p class="font-weight-bold">{{ $profil->tentang }}</p>
            @endisset
            @empty($profil)
              <span class="font-weight-bold">. . . . </span>
            @endempty
          </li>
        </ul>
      </div>
    </aside>
    <section class="col ml-5 bg-white px-0 border">
      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Riwayat</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Video Saya</a>
        </li>
      </ul>
      <div class="tab-content p-2" id="myTabContent">
        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
          @if (count($history) > 0)
          @foreach ($history as $pelajaran)
          <article class="card shadow-sm col px-0 mb-3">
            <div class="d-flex justify-content-between px-3 pt-3 pb-1">
              <p class="font-weight-bold">{{ $pelajaran->pelajaran }}</p>
              <time class="font-italic">{{ $pelajaran->created_at->format('d F Y') }}</time>
            </div>
            <div class="d-flex justify-content-between px-3 pt-1 pb-3">
              <p class="m-0">{{ $pelajaran->teachername }}</p>
              <span>Tarif : <var>{{ $pelajaran->lesco }} Lesco</var></span>
            </div>
            <div class="action bg-light text-center p-2">
              <a href="">Lihat Detail</a>
            </div>
          </article>
          @endforeach
          @else
          <div class="alert alert-warning text-capitalize col" role="alert">
            Kamu belum pernah memesan guru
          </div>
          @endif
        </div>
        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
          @if (count($videos) > 0)
          @foreach ($videos as $video)
          <div class="card-body p-2">
            <figure class="d-flex mb-3">
              <img class="col-md-4 px-0 border-right" height="150" src="{{ asset('sampul/'.$video->sampul)}}" style="object-fit: cover;">
              <figcaption class="col-md-8">
                <h5 class="card-title text-capitalize text-info show-modal">{{ $video->judul }}</h5>
                <div class="myoverlay">
                  <a href="javascript:void(0);" class="close-modal"><i class="bx bx-x"></i></a>
                  <div class="mymodal">
                    <video src="{{ asset('uploaded_video/'.$video->video) }}" poster="{{ asset('sampul/'.$video->sampur) }}" controls></video>
                  </div>
                </div>
                <p class="card-text">{{ $video->deskripsi }}</p>
                <var class="position-absolute text-warning" style="right: 1rem;top: 0;">{{ $video->lesco }} Lesco</var>
                <a href="{{route('murid.printSertifikat', ['id' => $video->id])}}" class="position-absolute" target="_blank" style="bottom: 10px;">Download Sertifikat</a>
              </figcaption>
            </figure>
          </div>
          @endforeach
          @else
          <div class="alert alert-warning text-capitalize col" role="alert">
            Kamu belum pernah memesan video
          </div>
          @endif
        </div>
      </div>
    </section>
  </div>
</div>

@endsection

@section('footer_all')

@include('partials.footer')

@endsection

resources/views/murid/resultMateri.blade.php
@extends('layouts.master_siswa')
@section('title', 'Hasil Pencarian')
@section('content')
<div class="container py-4" id="search_materi">
  <form method="POST" action="{{ route('murid.searchMateriPost') }}" class="my-3">
    @csrf
    <div class="form-group col-12 position-relative px-0">
      <input id="materi" type="text" class="form-control" name="materi" placeholder="Apa yang ingin kamu pelajari" required>
      <button type="submit" class="btn shadow-none" name="button"><i class='bx bx-search-alt'></i></button>
    </div>
  </form>
  @foreach($videos as $video)
    <form action="{{ route('murid.buyVideo') }}" method="POST">
      @csrf
      <input type="hidden" value="{{ $video->id }}" class="form-control" name="idvideo" id="idvideo">
      <input type="hidden" value="{{ $video->guru }}" class="form-control" name="guru" id="guru">
      <input type="hidden" value="{{ $video->judul }}" class="form-control" name="judul" id="judul">
      <input type="hidden" value="{{ $video->deskripsi }}" class="form-control" name="deskripsi" id="deskripsi">
      <input type="hidden" value="{{ $video->video }}" class="form-control" name="video" id="video">
      <input type="hidden" value="{{ $video->sampul }}" class="form-control" name="sampul" id="sampul">
      <input type="hidden" value="{{ $video->lesco }}" class="form-control" name="lesco" id="lesco">
      <div class="card p-0 col-12 shadow-sm mb-3">
        <div class="card-body p-0">
          <figure class="d-flex m-0">
            <img class="col-md-4 px-0 border-right" height="150" src="{{ asset('sampul/'.$video->sampul)}}" style="object-fit: cover;">
            <figcaption class="position-relative col py-3">
              <h5 class="card-title">{{ $video->judul }}</h5>
              <p class="card-text">{{ $video->deskripsi }}</p>
              <var>Harga {{ $video->lesco }} Lesco</var>
              <button type="submit" name="button" class="btn btn-success">Beli Video</button>
            </figcaption>
          </figure>
        </div>
      </div>
    </form>
  @endforeach
</div>
@endsection
@section('footer_all')
@include('partials.footer')
@endsection

resources/views/murid/topup.blade.php
<form action="{{ route('murid.depositMuridAction') }}" method="post">
  @csrf
  <h1 class="h4 mb-4 text-left">Nomor Rekening: <span class="font-weight-bold">0193184917987</span></h1>
  <div class="form-group">
    <select class="custom-select" name="lesco" required>
      <option value="" selected disabled>Pilih Nominal Isian</option>
      <option value="100">100</option>
      <option value="200">200</option>
      <option value="300">300</option>
      <option value="400">400</option>
      <option value="500">500</option>
      <option value="600">600</option>
      <option value="700">700</option>
      <option value="800">800</option>
      <option value="900">900</option>
      <option value="1000">1000</option>
    </select>
  </div>
  <button type="submit" class="btn btn-success float-left" name="button">Topup Sekarang</button>
</form>