routes/web.php
<?php

Auth::routes();
Route::view('/', 'homepage');
Route::get('home', 'HomeController@index')->name('home');

Route::middleware(['auth', 'MuridRole'])->group(function(){
	Route::prefix('murid')->group(function() {
		Route::name('murid.')->group(function(){
			Route::get('room', 'VideoRoomController@indexMurid')->name('room.index');
			Route::post('room/join', 'VideoRoomController@joinRoomMurid')->name('room.join');
			Route::get('dashboard','ProfileController@indexMurid')->name('index');
			Route::get('detail/{id}','OrderController@detailOrderMurid')->name('detail');
			Route::get('detail/delete/{id}', 'OrderController@hapusOrderan')->name('hapusOrderan');
			Route::get('les/offline/order','OrderController@createOffline')->name('createOffline');
			Route::post('les/offline/order','OrderController@createOfflinePost')->name('createOfflinePost');
			Route::put('les/offline/accept/{id}', 'OrderController@createOfflineAccepted')->name('createOfflineAccepted');
			Route::post('les/offline/finish','OrderController@createOfflineFinished')->name('createOfflineFinished');
			Route::get('les/online/order','OrderController@createOnline')->name('createOnline');
			Route::post('les/online/order','OrderController@createOnlinePost')->name('createOnlinePost');
			Route::get('les/materi/search','MateriController@searchMateri')->name('searchMateri');
			Route::post('les/materi/search','MateriController@searchMateriPost')->name('searchMateriPost');
			Route::get('materi/{id}','MateriController@materi')->name('materi');
			Route::get('materi/{id}/sertifikat','MateriController@printSertifikat')->name('printSertifikat');
			Route::get('task','OrderController@taskMurid')->name('taskMurid');
			Route::get('settings','HomeController@settingsMurid')->name('settingsMurid');
			Route::post('deposit','ProfileController@depositMuridAction')->name('depositMuridAction');
			Route::get('profile','ProfileController@profileMurid')->name('profileMurid');
			Route::get('isiprofile','ProfileController@isiProfileMurid')->name('isiProfileMurid');
			Route::post('isiprofile','ProfileController@isiProfileMuridAction')->name('isiProfileMuridAction');
			Route::get('updateprofile/{id}','ProfileController@updateProfileMurid')->name('updateProfileMurid');
			Route::post('updateprofile','ProfileController@updateProfileMuridAction')->name('updateProfileMuridAction');
			Route::post('buyvideo','MyVideosController@buyVideo')->name('buyVideo');
			Route::get('watch/{title}', 'MateriController@watchmateri')->name('watch');
		});
	});
});
Route::middleware(['auth', 'GuruRole'])->group(function(){
	Route::prefix('guru')->group(function(){
		Route::name('guru.')->group(function(){
			Route::get('room', 'VideoRoomController@indexGuru')->name('room.index');
			Route::get('room/join/{roomName}', 'VideoRoomController@joinRoom')->name('group.room.join');
			Route::post('room/create', 'VideoRoomController@createRoom')->name('room.create');
			Route::get('dashboard','ProfileController@indexGuru')->name('index');
			Route::get('les/offline/order','MateriController@searchOffline')->name('searchOffline');
			Route::get('les/offline/order/{id}','MateriController@searchOfflineDetail')->name('searchOfflineDetail');
			Route::post('les/offline/order','MateriController@searchOfflineAction')->name('searchOfflineTake');
			Route::get('les/offline/filter','MateriController@searchOfflineFilter')->name('searchOfflineFilter');
			Route::post('les/offline/proses','MateriController@searchOfflineProcess')->name('searchOfflineProses');
			Route::post('les/offline/finish','MateriController@searchOfflineFinished')->name('searchOfflineFinished');
			Route::get('les/online/order','MateriController@searchOnline')->name('searchOnline');
			Route::get('les/online/order/{id}','MateriController@searchOnlineDetail')->name('searchOnlineDetail');
			Route::get('les/materi/create','MateriController@createMateri')->name('createMateri');
			Route::post('les/materi/create','MateriController@createMateriPost')->name('createMateriPost');
			Route::get('task','OrderController@taskGuru')->name('taskGuru');
			Route::get('settings','HomeController@settingsGuru')->name('settingsGuru');
			Route::get('withdraw','ProfileController@withdrawGuru')->name('withdrawGuru');
			Route::post('withdraw','ProfileController@withdrawGuruAction')->name('withdrawGuruAction');
			Route::get('profile','ProfileController@profileGuru')->name('profileGuru');
			Route::get('isiprofile','ProfileController@isiProfileGuru')->name('isiProfileGuru');
			Route::post('isiprofile','ProfileController@isiProfileGuruAction')->name('isiProfileGuruAction');
			Route::get('updateprofile/{id}','ProfileController@updateProfileGuru')->name('updateProfileGuru');
			Route::post('updateprofile','ProfileController@updateProfileGuruAction')->name('updateProfileGuruAction');
		});
	});
});

resources/views/partials/footer.blade.php
  <div id="footer_content" class="py-4">
    <div class="container">
      <div class="row mx-0">
        <div class="col-12 col-md-7 px-0">
          <div class="row mx-0">
            <div class="col-12 col-md-6 px-0">
              <h3 style="font-weight: bolder;" class="mb-3">Tentang Ngeles</h3>
              <ul>
                <li><a href="">Tentang Kami</a></li>
                <li><a href="">Bantuan</a></li>
                <li><a href="">Kontak Kami</a></li>
              </ul>
            </div>
            <div class="col-12 col-md-6 px-0">
              <h3 style="font-weight: bolder;" class="mb-3">Produk</h3>
              <ul>
                <li><a href="">Les Offline</a></li>
                <li><a href="">Materi Offline</a></li>
                <li><a href="">Les Online</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-12 col-md-5 px-0">
          <h3 style="font-weight: bolder;" class="mb-3">Ikuti Kami</h3>
          <ul>
            <li><a href="">Facebook</a></li>
            <li><a href="">Twitter</a></li>
            <li><a href="">Linkedin</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div id="footer_legal" class="py-3">
    <div class="container">
      <div class="row mx-0">
        <small style="font-size: 17px;">Copyright &copy; Ngeles {{ date('Y') }} | All Rights Reserved</small>
      </div>
    </div>
  </div>

resources/views/partials/footer_bottom.blade.php
<div id="footer_legal" class="py-3">
  <div class="container">
    <div class="row mx-0">
      <small style="font-size: 17px;">Copyright &copy; Ngeles {{ date('Y') }} | All Rights Reserved</small>
    </div>
  </div>
</div>

resources/views/partials/footer_top.blade.php
<div id="footer_content" class="py-4">
  <div class="container">
    <div class="row mx-0">
      <div class="col-12 col-md-7 px-0">
        <div class="row mx-0">
          <div class="col-12 col-md-6 px-0">
            <h3 class="font-weight-bold text-white mb-3">Tentang Ngeles</h3>
            <ul>
              <li><a href="">Tentang Kami</a></li>
              <li><a href="">Bantuan</a></li>
              <li><a href="">Kontak Kami</a></li>
            </ul>
          </div>
          <div class="col-12 col-md-6 px-0">
            <h3 class="font-weight-bold text-white mb-3">Produk</h3>
            <ul>
              <li><a href="">Les Offline</a></li>
              <li><a href="">Materi Offline</a></li>
              <li><a href="">Les Online</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-12 col-md-5 px-0">
        <h3 class="font-weight-bold text-white mb-3">Ikuti Kami</h3>
        <ul>
          <li><a href="">Facebook</a></li>
          <li><a href="">Twitter</a></li>
          <li><a href="">Linkedin</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

resources/views/partials/navbar.blade.php
<nav class="navbar navbar-expand-lg">
  @auth
    @if (Auth::user()->role == 'Murid')
    <a class="navbar-brand text-uppercase mr-0" href="{{ route('murid.index') }}">Lesin</a>
    @elseif (Auth::user()->role == 'Guru')
    <a class="navbar-brand text-uppercase mr-0" href="{{ route('guru.index') }}">Lesin</a>
    @endif
  @endauth
  @guest
  <a class="navbar-brand text-uppercase" href="{{ url('/') }}">Lesin</a>
  @endguest
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"><i class='bx bx-menu'></i></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarTogglerDemo02">
    <ul class="navbar-nav mt-2 mt-lg-0">
      @guest
      <li class="nav-item">
        <a class="nav-link" href="{{ route('login') }}">Login</a>
      </li>
      @endguest
      @auth
        @if (Auth::user()->role == 'Murid')
          <li class="nav-item dropdown">
            @if (\Request::is('murid/dashboard'))
              @empty($profil)
              <li class="nav-item">
                <a class="nav-link disabled" href="{{ route('murid.taskMurid') }}">Ranselku</a>
              </li>
              <li class="nav-item">
                <a class="nav-link dropdown-toggle disabled" href="#" id="dropdown_menu_les_murid" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Mulai Les
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdown_menu_les_murid">
                  <a class="nav-link" href="{{ route('murid.createOffline') }}">Temukan Guru</a>
                  <a class="nav-link" href="{{ route('murid.searchMateri') }}">Jelajah Materi</a>
                  <a class="nav-link" href="{{ route('murid.createOnline') }}">Les Online</a>
                  <a class="nav-link" href="{{ route('murid.room.index') }}">Video Konferensi</a>
                </div>
              </li>
              @endempty
              @isset($profil)
              <li class="nav-item">
                <a class="nav-link" href="{{ route('murid.taskMurid') }}">Ranselku</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown_menu_les_murid" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Mulai Les
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdown_menu_les_murid">
                  <a class="nav-link" href="{{ route('murid.createOffline') }}">Temukan Guru</a>
                  <a class="nav-link" href="{{ route('murid.searchMateri') }}">Jelajah Materi</a>
                  <a class="nav-link" href="{{ route('murid.createOnline') }}">Les Online</a>
                  <a class="nav-link" href="{{ route('murid.room.index') }}">Video Konferensi</a>
                </div>
              </li>
              @endisset
            @else
              @if (\Request::is('/'))
                <li class="nav-item">
                  <a class="nav-link" href="{{ route('murid.taskMurid') }}">Ranselku</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="dropdown_menu_les_murid" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Mulai Les
                  </a>
                  <div class="dropdown-menu" aria-labelledby="dropdown_menu_les_murid">
                    <a class="nav-link" href="{{ route('murid.createOffline') }}">Temukan Guru</a>
                    <a class="nav-link" href="{{ route('murid.searchMateri') }}">Jelajah Materi</a>
                    <a class="nav-link" href="{{ route('murid.createOnline') }}">Les Online</a>
                    <a class="nav-link" href="{{ route('murid.room.index') }}">Video Konferensi</a>
                  </div>
                </li>
              @else
                @empty ($profil)
                <li class="nav-item">
                  <a class="nav-link disabled" href="{{ route('murid.taskMurid') }}">Ranselku</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="dropdown_menu_les_murid" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Mulai Les
                  </a>
                  <div class="dropdown-menu disabled" aria-labelledby="dropdown_menu_les_murid">
                    <a class="nav-link" href="{{ route('murid.createOffline') }}">Temukan Guru</a>
                    <a class="nav-link" href="{{ route('murid.searchMateri') }}">Jelajah Materi</a>
                    <a class="nav-link" href="{{ route('murid.createOnline') }}">Les Online</a>
                    <a class="nav-link" href="{{ route('murid.room.index') }}">Video Konferensi</a>
                  </div>
                </li>
                @endempty
                @isset($profil)
                <li class="nav-item">
                  <a class="nav-link" href="{{ route('murid.taskMurid') }}">Ranselku</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="dropdown_menu_les_murid" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Mulai Les
                  </a>
                  <div class="dropdown-menu disabled" aria-labelledby="dropdown_menu_les_murid">
                    <a class="nav-link" href="{{ route('murid.createOffline') }}">Temukan Guru</a>
                    <a class="nav-link" href="{{ route('murid.searchMateri') }}">Jelajah Materi</a>
                    <a class="nav-link" href="{{ route('murid.createOnline') }}">Les Online</a>
                    <a class="nav-link" href="{{ route('murid.room.index') }}">Video Konferensi</a>
                  </div>
                </li>
                @endisset
              @endif
            @endif
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown_menu_logout_murid" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ Auth::user()->username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdown_menu_logout_murid">
            <a href="{{ route('murid.profileMurid') }}" class="nav-link">Profile</a>
                <a href="" class="nav-link">Setting</a>
                <a class="nav-link" href="{{ route('logout') }}" onclick="event.preventDefault();
                document.getElementById('logout-form').submit();">Logout</a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                    @csrf
                </form>
              </div>
          </li>
        @elseif (Auth::user()->role == 'Guru')
          @if (\Request::is('guru/dashboard'))
            @isset($profil)
            <li class="nav-item">
              <a class="nav-link" href="{{ route('guru.taskGuru') }}">Tugasku</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown_menu_les_guru" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Mulai Mengajar
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdown_menu_les_guru">
                    <a class="nav-link text-info" href="{{ route('guru.searchOffline') }}">Cari Murid</a>
                    <a class="nav-link text-info" href="{{ route('guru.createMateri') }}">Buat Materi</a>
                    <a class="nav-link text-info" href="{{ route('guru.searchOnline') }}">Ngajar Online</a>
                    <a class="nav-link text-info" href="{{ route('guru.room.index') }}">Video Konferensi</a>
                </div>
            </li>
            @endisset
            @empty($profil)
            <li class="nav-item">
              <a class="nav-link disabled" tabindex="-1" role="button" href="#" aria-disabled="true">Tugasku</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle disabled" tabindex="-1" role="button" href="#" id="dropdown_menu_les_guru" role="button" aria-disabled="true">
                Mulai Mengajar
              </a>
            </li>
            @endempty
          @else
            @if (\Request::is('/'))
              <li class="nav-item">
                <a class="nav-link disabled" tabindex="-1" role="button" aria-disabled="true" href="#">Tugasku</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle disabled" href="#" id="dropdown_menu_les_guru" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Mulai Mengajar
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdown_menu_les_guru">
                  <a class="nav-link" href="{{ route('guru.searchOffline') }}">Temukan Murid</a>
                  <a class="nav-link" href="{{ route('guru.createMateri') }}">Buat Materi</a>
                  <a class="nav-link" href="{{ route('guru.searchOnline') }}">Ngajar Online</a>
                  <a class="nav-link" href="{{ route('guru.room.index') }}">Video Konferensi</a>
                </div>
              </li>
            @else
              @isset($profil)
                <li class="nav-item">
                  <a class="nav-link" href="{{ route('guru.taskGuru') }}">Tugasku</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="dropdown_menu_les_guru" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Mulai Mengajar
                  </a>
                  <div class="dropdown-menu" aria-labelledby="dropdown_menu_les_guru">
                    <a class="nav-link" href="{{ route('guru.searchOffline') }}">Temukan Murid</a>
                    <a class="nav-link" href="{{ route('guru.createMateri') }}">Buat Materi</a>
                    <a class="nav-link" href="{{ route('guru.searchOnline') }}">Ngajar Online</a>
                    <a class="nav-link" href="{{ route('guru.room.index') }}">Video Konferensi</a>
                  </div>
                </li>
              @endisset
              @empty ($profil)
                <li class="nav-item">
                  <a class="nav-link" href="{{ route('guru.taskGuru') }}">Tugasku</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="dropdown_menu_les_guru" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Mulai Mengajar
                  </a>
                  <div class="dropdown-menu" aria-labelledby="dropdown_menu_les_guru">
                    <a class="nav-link" href="{{ route('guru.searchOffline') }}">Temukan Murid</a>
                    <a class="nav-link" href="{{ route('guru.createMateri') }}">Buat Materi</a>
                    <a class="nav-link" href="{{ route('guru.searchOnline') }}">Ngajar Online</a>
                    <a class="nav-link" href="{{ route('guru.room.index') }}">Video Konferensi</a>
                  </div>
                </li>
              @endempty
            @endif
          @endif
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown_menu_logout_guru" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ Auth::user()->username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdown_menu_logout_guru">
              <a href="{{ route('guru.profileGuru') }}" class="nav-link">Profile</a>
              <a href="" class="nav-link">Setting</a>
              <a class="nav-link" href="{{ route('logout') }}" onclick="event.preventDefault();
                       document.getElementById('logout-form').submit();">Logout</a>
              <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                @csrf
              </form>
            </div>
          </li>
        @endif
      @endauth
    </ul>
  </div>
</nav>