routes/web.php
<?php

Auth::routes();
Route::view('/', 'homepage');
Route::get('home', 'HomeController@index')->name('home');

Route::middleware(['auth', 'MuridRole'])->group(function(){
	Route::prefix('murid')->group(function() {
		Route::name('murid.')->group(function(){
			Route::get('room', 'VideoRoomController@indexMurid')->name('room.index');
			Route::post('room/join', 'VideoRoomController@joinRoomMurid')->name('room.join');
			Route::get('dashboard','ProfileController@indexMurid')->name('index');
			Route::get('detail/{id}','OrderController@detailOrderMurid')->name('detail');
			Route::get('detail/delete/{id}', 'OrderController@hapusOrderan')->name('hapusOrderan');
			Route::get('les/offline/order','OrderController@createOffline')->name('createOffline');
			Route::post('les/offline/order','OrderController@createOfflinePost')->name('createOfflinePost');
			Route::put('les/offline/accept/{id}', 'OrderController@createOfflineAccepted')->name('createOfflineAccepted');
			Route::post('les/offline/finish','OrderController@createOfflineFinished')->name('createOfflineFinished');
			Route::get('les/online/order','OrderController@createOnline')->name('createOnline');
			Route::post('les/online/order','OrderController@createOnlinePost')->name('createOnlinePost');
			Route::get('les/materi/search','MateriController@searchMateri')->name('searchMateri');
			Route::post('les/materi/search','MateriController@searchMateriPost')->name('searchMateriPost');
			Route::get('materi/{id}','MateriController@materi')->name('materi');
			Route::get('materi/{id}/sertifikat','MateriController@printSertifikat')->name('printSertifikat');
			Route::get('task','OrderController@taskMurid')->name('taskMurid');
			Route::get('settings','HomeController@settingsMurid')->name('settingsMurid');
			Route::post('deposit','ProfileController@depositMuridAction')->name('depositMuridAction');
			Route::get('profile','ProfileController@profileMurid')->name('profileMurid');
			Route::get('isiprofile','ProfileController@isiProfileMurid')->name('isiProfileMurid');
			Route::post('isiprofile','ProfileController@isiProfileMuridAction')->name('isiProfileMuridAction');
			Route::get('updateprofile/{id}','ProfileController@updateProfileMurid')->name('updateProfileMurid');
			Route::post('updateprofile','ProfileController@updateProfileMuridAction')->name('updateProfileMuridAction');
			Route::post('buyvideo','MyVideosController@buyVideo')->name('buyVideo');
			Route::get('watch/{title}', 'MateriController@watchmateri')->name('watch');
		});
	});
});
Route::middleware(['auth', 'GuruRole'])->group(function(){
	Route::prefix('guru')->group(function(){
		Route::name('guru.')->group(function(){
			Route::get('room', 'VideoRoomController@indexGuru')->name('room.index');
			Route::get('room/join/{roomName}', 'VideoRoomController@joinRoom')->name('group.room.join');
			Route::post('room/create', 'VideoRoomController@createRoom')->name('room.create');
			Route::get('dashboard','ProfileController@indexGuru')->name('index');
			Route::get('les/offline/order','MateriController@searchOffline')->name('searchOffline');
			Route::get('les/offline/order/{id}','MateriController@searchOfflineDetail')->name('searchOfflineDetail');
			Route::post('les/offline/order','MateriController@searchOfflineAction')->name('searchOfflineTake');
			Route::get('les/offline/filter','MateriController@searchOfflineFilter')->name('searchOfflineFilter');
			Route::post('les/offline/proses','MateriController@searchOfflineProcess')->name('searchOfflineProses');
			Route::post('les/offline/finish','MateriController@searchOfflineFinished')->name('searchOfflineFinished');
			Route::get('les/online/order','MateriController@searchOnline')->name('searchOnline');
			Route::get('les/online/order/{id}','MateriController@searchOnlineDetail')->name('searchOnlineDetail');
			Route::get('les/materi/create','MateriController@createMateri')->name('createMateri');
			Route::post('les/materi/create','MateriController@createMateriPost')->name('createMateriPost');
			Route::get('task','OrderController@taskGuru')->name('taskGuru');
			Route::get('settings','HomeController@settingsGuru')->name('settingsGuru');
			Route::get('withdraw','ProfileController@withdrawGuru')->name('withdrawGuru');
			Route::post('withdraw','ProfileController@withdrawGuruAction')->name('withdrawGuruAction');
			Route::get('profile','ProfileController@profileGuru')->name('profileGuru');
			Route::get('isiprofile','ProfileController@isiProfileGuru')->name('isiProfileGuru');
			Route::post('isiprofile','ProfileController@isiProfileGuruAction')->name('isiProfileGuruAction');
			Route::get('updateprofile/{id}','ProfileController@updateProfileGuru')->name('updateProfileGuru');
			Route::post('updateprofile','ProfileController@updateProfileGuruAction')->name('updateProfileGuruAction');
		});
	});
});

resources/views/vidcon/guru-index.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Video Conference</title>
	<link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
	<link rel="stylesheet" href="{{ asset('css/vidkon.css') }}">
</head>
<body>
	@include('partials.navbar')
	<main class="card shadow-sm mx-auto p-4">
		<h1 class="h4 mb-4 text-center">Selamat Datang Divideo Konferensi <strong>Ngeles</strong></h1>
		<form action="{{ route('guru.room.create') }}" class="form-inline justify-content-center" method="post">
            @csrf
				<input type="text" class="form-control col-4 mr-4" name="roomName" placeholder="Room Name" autofocus required>
				<input id="room_password" type="password" class="form-control col-4 mr-4" name="room_password" placeholder="Password" required>
				@if ($errors->has('room_password'))
				<span class="invalid-feedback mr-2" role="alert">
				 <strong>{{ $errors->first('room_password') }}</strong>
				</span>
				@endif
			<button type="submit" name="button" class="btn btn-primary">Membuat Room</button>
		</form>
	</main>
	<script src="{{ asset('js/jquery.js') }}" charset="utf-8"></script>
	<script src="{{ asset('js/popper.min.js') }}" charset="utf-8"></script>
	<script src="{{ asset('js/bootstrap.min.js') }}" charset="utf-8"></script>
	<script src="{{ asset('js/guru.js') }}" charset="utf-8"></script>
</body>
</html>

resources/views/vidcon/index.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Video Conference</title>
	<link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
	<link rel="stylesheet" href="{{ asset('css/vidkon.css') }}">
</head>
<body>
	@include('partials.navbar')
	<main class="card shadow-sm mx-auto p-4">
		<h1 class="h4 mb-4 text-center">Selamat Datang Divideo Konferensi <strong>Ngeles</strong></h1>
		<form action="{{ route('group.room.create') }}" class="form-inline justify-content-center" method="post">
				<input type="text" class="form-control col-4 mr-4" id="roomName" name="roomName" placeholder="Room Name" autofocus required>
				<input id="room_password" type="password" class="form-control col-4 mr-4" name="room_password" placeholder="Password" required>
				@if ($errors->has('room_password'))
				<span class="invalid-feedback mr-2" role="alert">
				 <strong>{{ $errors->first('room_password') }}</strong>
				</span>
				@endif
			<button type="submit" name="button" class="btn btn-primary">Bergabung Sekarang</button>
		</form>
	</main>
	<script src="{{ asset('js/jquery.js') }}" charset="utf-8"></script>
	<script src="{{ asset('js/popper.min.js') }}" charset="utf-8"></script>
	<script src="{{ asset('js/bootstrap.min.js') }}" charset="utf-8"></script>
</body>
</html>

resources/views/vidcon/murid-index.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Video Conference</title>
	<link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
	<link rel="stylesheet" href="{{ asset('css/vidkon.css') }}">
</head>
<body>
	@include('partials.navbar')
	<main class="card shadow-sm mx-auto p-4">
		<h1 class="h4 mb-4 text-center">Selamat Datang Divideo Konferensi <strong>Ngeles</strong></h1>
		<form action="{{ route('murid.room.join') }}" class="form-inline justify-content-center" method="post">
            @csrf
				<input type="text" class="form-control col-4 mr-4" name="roomName" placeholder="Room Name" autofocus required>
				<input id="room_password" type="password" class="form-control col-4 mr-4" name="room_password" placeholder="Password" required>
				@if ($errors->has('room_password'))
				<span class="invalid-feedback mr-2" role="alert">
				 <strong>{{ $errors->first('room_password') }}</strong>
				</span>
				@endif
			<button type="submit" name="button" class="btn btn-primary">Bergabung Sekarang</button>
		</form>
	</main>
	<script src="{{ asset('js/jquery.js') }}" charset="utf-8"></script>
	<script src="{{ asset('js/popper.min.js') }}" charset="utf-8"></script>
	<script src="{{ asset('js/bootstrap.min.js') }}" charset="utf-8"></script>
	<script>
		$(document).ready(function() {
			​$('input[name="roomName"]').keypress(function( e ) {
				if(e.which === 32)
					return false;
			})​​​​​;​
		});
	</script>
</body>
</html>

resources/views/vidcon/room.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
        <script src="//media.twiliocdn.com/sdk/js/video/v1/twilio-video.min.js"></script>
        <script>
            Twilio.Video.createLocalTracks({
            audio: true,
            video: { width: 300 }
            }).then(function(localTracks) {
            return Twilio.Video.connect('{{ $accessToken }}', {
                name: '{{ $roomName }}',
                tracks: localTracks,
                video: { width: 300 }
            });
            }).then(function(room) {
            console.log('Successfully joined a Room: ', room.name);

            room.participants.forEach(participantConnected);

            var previewContainer = document.getElementById(room.localParticipant.sid);
            if (!previewContainer || !previewContainer.querySelector('video')) {
                participantConnected(room.localParticipant);
            }

            room.on('participantConnected', function(participant) {
                // console.log("Joining: '"   participant.identity   "'");
                participantConnected(participant);
            });

            room.on('participantDisconnected', function(participant) {
                // console.log("Disconnected: '"   participant.identity   "'");
                participantDisconnected(participant);
            });
            });
            // additional functions will be added after this point
        </script>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            @if (Route::has('login'))
                <div class="top-right links">
                    @auth
                        <a href="{{ url('/home') }}">Home</a>
                    @else
                        <a href="{{ route('login') }}">Login</a>

                        @if (Route::has('register'))
                            <a href="{{ route('register') }}">Register</a>
                        @endif
                    @endauth
                </div>
            @endif

            <div id="media-div">
            </div>
        </div>
    </body>
    <script>
        function participantConnected(participant) {
            // console.log('Participant "%s" connected', participant.identity);

            const div = document.createElement('div');
            div.id = participant.sid;
            div.setAttribute("style", "float: left; margin: 10px;");
            // div.innerHTML = "<div style='clear:both'>" participant.identity "</div>";

            participant.tracks.forEach(function(track) {
                trackAdded(div, track)
            });

            participant.on('trackAdded', function(track) {
                trackAdded(div, track)
            });
            participant.on('trackRemoved', trackRemoved);

            document.getElementById('media-div').appendChild(div);
        }

        function participantDisconnected(participant) {
            console.log('Participant "%s" disconnected', participant.identity);

            participant.tracks.forEach(trackRemoved);
            document.getElementById(participant.sid).remove();
        }

        function trackAdded(div, track) {
            div.appendChild(track.attach());
            var video = div.getElementsByTagName("video")[0];
            if (video) {
                video.setAttribute("style", "max-width:300px;");
            }
        }

        function trackRemoved(track) {
            track.detach().forEach( function(element) { element.remove() });
        }
    </script>
</html>